services:
    localstack:
        image: localstack/localstack:0.12.5
        container_name: localstack
        platform: linux/amd64
        ports:
            - "4566:4566"
            - "4572:4572"
        volumes:
            - "./localstack:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
        env_file:
            - .env
    